---
version: '3.3'
services:
  app:
      image: rodrigorootrj/service:python-playground-1.42.01
      volumes:
      - type: bind
        source: $PWD/src
        target: /app/
      restart: always
      command: python main.py
      depends_on:
         - db
  db:
    image: mysql
    volumes:
      - db:/var/lib/mysql 
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass 
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_ALLOW_EMPTY_PASSWORD: not
      MYSQL_RANDOM_ROOT_PASSWORD : not
    restart: always

  grafana:
    image: grafana/grafana-enterprise
    volumes:
      - grafana:/var/lib/grafana     
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  db:
  grafana: